ARG BASE_IMAGE="registry.fedoraproject.org/fedora-toolbox:40"
FROM $BASE_IMAGE

RUN dnf -y install dnf-plugins-core \
	&& dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo \
	&& dnf install --refresh -y \
		docker-ce \
		docker-ce-cli \
		containerd.io \
		docker-buildx-plugin \
		docker-compose-plugin \
		buildah \
		podman \
		skopeo \
		gpg \
		dumb-init \
		git

ENTRYPOINT ["/usr/bin/dumb-init", "--"]

STOPSIGNAL SIGTERM
