---
# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
stages:
  - name: blue-build
    from: rust
    modules:
      - type: script
        scripts:
          - bluebuild.sh
modules:
  - type: copy
    from: blue-build
    src: /out/bluebuild
    dest: /usr/bin/bluebuild
