stages:
  - name: blue-build
    image: rust
    modules:
      - type: containerfile
        snippets:
          - |
            RUN cargo install blue-build --debug --all-features --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/bluebuild /out/bluebuild
modules:
  - type: copy
    from: blue-build
    src: /out/bluebuild
    dest: /usr/bin/bluebuild
