---
# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
stages:
  - name: ubuntu-test
    from:
      - ubuntu
    modules: {}
  - name: debian-test
    from: debian
    modules:
      - from-file: stages.yml
  - name: fedora-test
    from: fedora
    modules:
      - from-file: stages.yml
  - name: alpine-test
    from: alpine
    modules:
      - from-file: stages.yml
modules:
  - type: files
    files:
      - usr: /usr
  - type: script
    scripts:
      - example.sh
    snippets:
      - echo "test" > /test.txt
  - type: test-module
    source: local
  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet"
  - type: rpm-ostree
    install: micro
