---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cli/test
description: This is my personal OS image.
base-image: quay.io/fedora/fedora-bootc
blue-build-tag: none
cosign-version: none
image-version: latest
stages:
  - from-file: stages.yml
modules:
  - from-file: common.yml
