name: cli/test
alt-tags:
  - gts
  - stable
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39
stages:
  - name: blue-build
    image: rust
    modules:
      - type: containerfile
        snippets:
          - |
            RUN cargo install blue-build --debug --all-features --target x86_64-unknown-linux-gnu \
              && mkdir -p /out/ \
              && mv $CARGO_HOME/bin/bluebuild /out/bluebuild
modules:
  - from-file: akmods.yml
  - from-file: flatpaks.yml

  - type: files
    files:
      - usr: /usr

  - type: script
    scripts:
      - example.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: signing

  - type: test-module

  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet" && ostree container commit

  - type: copy
    from: blue-build
    src: /out/bluebuild
    dest: /usr/bin/bluebuild
