---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cli/test
description: This is my personal OS image.
base-image: quay.io/fedora/fedora-silverblue
image-version: latest
alt-tags:
  - arm64
stages:
  - from-file: stages.yml
modules:
  - from-file: flatpaks.yml

  - type: files
    files:
      - usr: /usr

  - type: script
    scripts:
      - example.sh

  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: signing

  - type: test-module
    source: local

  - type: test-nu-modules
    source: local
    test-prop:
      - this
      - is
      - a
      - test

  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet" && ostree container commit

  - type: copy
    from: alpine-test
    src: /test.txt
    dest: /
  - type: copy
    from: ubuntu-test
    src: /test.txt
    dest: /
  - type: copy
    from: debian-test
    src: /test.txt
    dest: /
  - type: copy
    from: fedora-test
    src: /test.txt
    dest: /
