name: cli/test
description: This is my personal OS image.
base-image: quay.io/fedora/fedora-silverblue
image-version: 40
alt_tags:
  - arm64
stages:
modules:
  - from-file: akmods.yml
  - from-file: flatpaks.yml

  - type: files
    files:
      - usr: /usr

  - type: script
    scripts:
      - example.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: signing

  - type: test-module

  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet" && ostree container commit
