---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: cli/test
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
stages:
  - from-file: stages.yml
modules:
  - from-file: akmods.yml
  - from-file: flatpaks.yml

  - type: files
    files:
      - source: usr
        destination: /usr

  - type: script
    scripts:
      - example.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: signing
    source: ghcr.io/blue-build/modules:signing-switch-fully-to-etc
    
  - type: test-module
    source: local

  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet" && ostree container commit

  - type: copy
    from: alpine-test
    src: /test.txt
    dest: /
  - type: copy
    from: ubuntu-test
    src: /test.txt
    dest: /
  - type: copy
    from: debian-test
    src: /test.txt
    dest: /
  - type: copy
    from: fedora-test
    src: /test.txt
    dest: /
