---
# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
stages:
  - name: ubuntu-test
    from: ubuntu
    modules:
      - from-file: stages.yml
      - type: apt
        source: ghcr.io/blue-build/modules/apt:pr-523
        install:
          packages:
            - git
  - name: debian-test
    from: debian
    modules:
      - from-file: stages.yml
      - type: apt
        source: ghcr.io/blue-build/modules/apt:pr-523
        install:
          packages:
            - git
  - name: fedora-test
    from: fedora
    platform: linux/amd64
    modules:
      - from-file: stages.yml
      - type: dnf
        install:
          packages:
            - git
  - name: alpine-test
    from: alpine
    modules:
      - from-file: stages.yml
      - type: apk
        source: ghcr.io/blue-build/modules/apk:pr-523
        install:
          packages:
            - git
  - name: arch-test
    from: archlinux/archlinux
    modules:
      - from-file: stages.yml
      - type: pacman
        source: ghcr.io/blue-build/modules/pacman:pr-523
        install:
          packages:
            - git
  - name: suse-test
    from: opensuse/tumbleweed
    modules:
      - from-file: stages.yml
      - type: zypper
        source: ghcr.io/blue-build/modules/zypper:pr-523
        install:
          packages:
            - git
modules:
  - type: files
    files:
      - source: usr
        destination: /usr
  - type: script
    scripts:
      - example.sh
    snippets:
      - echo "test" > /test.txt
  - type: test-module
    source: local
  - type: containerfile
    containerfiles:
      - labels
    snippets:
      - RUN echo "This is a snippet"
  - type: test-nu-modules
    source: local
    test-prop:
      - this
      - is
      - a
      - test
