#!/bin/sh

print_version_json() {
  local version="1.24.0"
  printf '{"version": "%s"}\n' "$version"
}

main() {
  if [[ "$1" == "version" && "$2" == "--json" ]]; then
    print_version_json
  else
    echo 'Running buildah'
  fi
}

main "$@"
