#!/bin/sh

print_version_json() {
  local version="4.0.0"
  printf '{"Client":{"Version": "%s"}}\n' "$version"
}

main() {
  if [[ "$1" == "version" && "$2" == "-f" && "$3" == "json" ]]; then
    print_version_json
  else
    echo 'Running podman'
  fi
}

main "$@"
