#!/bin/bash

set -euo pipefail

if [ "$1" = "rebase" ]; then
  if [ "$2" = "ostree-unverified-image:oci-archive:$BB_TEST_LOCAL_IMAGE" ]; then
    echo "Rebased to local image $BB_TEST_LOCAL_IMAGE"
  else
   echo "Failed to rebase"
   exit 1
  fi
elif [ "$1" = "upgrade" ]; then
  echo "Performing upgrade for $BB_TEST_LOCAL_IMAGE"
elif [ "$1" = "status" ]; then
  cat <<EOF
{
  "deployments": [
    {
      "container-image-reference": "ostree-image-signed:docker://ghcr.io/blue-build/cli/test",
      "booted": true,
      "staged": false
    },
    {
      "container-image-reference": "ostree-image-signed:docker://ghcr.io/blue-build/cli/test:last",
      "booted": false,
      "staged": false
    }
  ]
}
EOF
else
  echo "Arg $1 is not recognized"
  exit 1
fi
