# TODO: Add back installs after upstream issues are fixed

modules:
  # Tests installing rpms from a combo image stage
  - type: akmods
    base: surface
    nvidia-version: 545
    # install:
    #   - nvidia
    #   - openrazer
    #   - openrgb

  # Tests pulling main image
  - type: akmods

  # Tests pulling image for main nvidia
  - type: akmods
    nvidia-version: 545

  # Test pulling image for base asus
  - type: akmods
    base: asus
