on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
      fork_pr:
        default: false
        type: boolean
    secrets:
      SIGNING_SECRET:
        required: true
        description: The cosign private key used to sign images
env:
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1
  RUST_LOG_STYLE: always

permissions: {}

jobs:
  arm64-prebuild:
    timeout-minutes: 20
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write # write pacakges to ghcr

    steps:
      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        if: ${{ ! inputs.fork_pr }}
        with:
          use-cache: false

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        if: ${{ ! inputs.fork_pr }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ ! inputs.fork_pr }}
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}


      - name: Login to GitHub Container Registry
        if: ${{ ! inputs.fork_pr }}
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run build
        if: ${{ ! inputs.fork_pr }}
        id: build
        run: |
          just image-prebuild-publish

  amd64-prebuild:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      packages: write # write pacakges to ghcr

    steps:
      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        if: ${{ ! inputs.fork_pr }}
        with:
          use-cache: false

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        if: ${{ ! inputs.fork_pr }}

      # Setup repo and add caching
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ ! inputs.fork_pr }}
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        if: ${{ ! inputs.fork_pr }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}


      - name: Run build
        id: build
        if: ${{ ! inputs.fork_pr }}
        run: |
          just image-prebuild-publish

  build-images:
    permissions:
      packages: write # push images to ghcr
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.image_manifest_metadata.outputs.digests }}
    needs:
      - arm64-prebuild
      - amd64-prebuild

    steps:
      - name: Maximize build space
        uses: hastd/free-disk-space@68572aeaadb7f76bd408246328e95926323402b5 # v0.1.2
        with:
          skip-if-available: "64G"

      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          use-cache: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      # Setup repo and add caching
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        if: ${{ ! inputs.fork_pr }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run build
        if: ${{ ! inputs.fork_pr }}
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ github.token }}
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          if [ -n "${COSIGN_PRIVATE_KEY}" ]; then
            just image-sign-publish
          else
            just image-publish
          fi

      - name: Run build
        if: ${{ inputs.fork_pr }}
        run: |
          just image-build

      - name: Store image digest info
        if: ${{ ! inputs.fork_pr }}
        id: image_manifest_metadata
        run: |
          digest_list_json=$(jq -Rc '[ inputs | split(",") | {"image_ref":.[0],"image_digest":.[1]} ]' ./digest-list)
          echo "digests=$digest_list_json" >> $GITHUB_OUTPUT

  provenance:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    needs: [build-images]
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    strategy:
      matrix:
        include: ${{ fromJson(needs.build-images.outputs.digests) }}
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ matrix.image_ref }}
      digest: ${{ matrix.image_digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
