name: Main branch build

concurrency: 
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    if: github.repository == 'blue-build/cli'
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repo: ${{ github.repository }}
      ref: main
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      repo: ${{ github.repository }}
      ref: main
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}