on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
      run:
        required: true
        type: string
      pr_event_number:
        type: string
      fork_pr:
        default: false
        type: boolean
      registry_login:
        default: false
        type: boolean
      install_qemu:
        default: false
        type: boolean
      install_docker:
        default: false
        type: boolean
      install_earthbuild:
        default: false
        type: boolean
    secrets:
      TEST_SIGNING_SECRET:
        required: true
        description: The cosign private key used to sign images for tests
env:
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1
  RUST_LOG_STYLE: always

permissions: {}

jobs:
  run-test:
    name: ${{ inputs.run }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read # read repo contents
      packages: write # write test package to ghcr
      id-token: write # docker auth

    steps:
      - name: Maximize build space
        uses: hastd/free-disk-space@68572aeaadb7f76bd408246328e95926323402b5 # v0.1.2
        with:
          skip-if-available: "64G"

      - name: Set up Docker Buildx
        if: ${{ inputs.install_docker }}
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          install: true

      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        if: ${{ inputs.install_earthbuild }}
        with:
          use-cache: false

      - name: Set up QEMU
        if: ${{ inputs.install_qemu }}
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        if: ${{ ! inputs.fork_pr && inputs.registry_login }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Setup repo and add caching
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Run ${{ inputs.run }}
        if: ${{ ! inputs.fork_pr }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_PR_EVENT_NUMBER: ${{ inputs.pr_event_number }}
          COSIGN_PRIVATE_KEY: ${{ secrets.TEST_SIGNING_SECRET }}
          RUN_JUST_RECIPE: ${{ inputs.run }}
        run: just "${RUN_JUST_RECIPE}"

      - name: Run ${{ inputs.run }} Fork PR
        if: ${{ inputs.fork_pr }}
        env:
          GH_PR_EVENT_NUMBER: ${{ inputs.pr_event_number }}
          RUN_JUST_RECIPE: ${{ inputs.run }}
        run: |
          export CARGO_HOME=$HOME/.cargo
          just "${RUN_JUST_RECIPE}"

