on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
      pr_event_number:
        type: string
      fork_pr:
        default: false
        type: boolean
    secrets:
      TEST_SIGNING_SECRET:
        required: true
        description: The cosign private key used to sign images for tests
env:
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1
  RUST_LOG_STYLE: always

permissions:
  contents: read # read repo contents
  packages: write # write test package to ghcr
  id-token: write # docker auth

jobs:
  test:
    timeout-minutes: 40
    runs-on: ubuntu-latest

    steps:
      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          use-cache: false

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}

      - name: Run build
        id: build
        run: |
          earth --ci +test

  lint:
    timeout-minutes: 40
    runs-on: ubuntu-latest

    steps:
      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          use-cache: false

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}


      - name: Run build
        id: build
        run: |
          earth --ci +lint

  integration-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: hastd/free-disk-space@68572aeaadb7f76bd408246328e95926323402b5 # v0.1.2
        with:
          skip-if-available: "64G"

      - uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          use-cache: false

      # Setup repo and add caching
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}


      - name: Run integration tests
        run: |
          earth bootstrap
          earth --ci -P ./integration-tests+all

  docker-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_docker: true
      run: test-docker-build

  recipe-v2:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-recipe-v2-build

  empty-files-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-empty-files-build

  env-expand-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-env-expansion-build

  bluefin-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-bluefin-build

  chunkah-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-chunkah-build

  build-chunked-oci-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-build-chunked-oci-build

  rechunk-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-rechunk-build

  arm64-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-arm64-build

  docker-build-external-login:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      registry_login: true
      install_docker: true
      run: test-docker-build-external-login

  podman-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-podman-build

  buildah-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-buildah-build

  multi-platform-docker:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_docker: true
      install_qemu: true
      run: test-multiplatform-docker

  multi-platform-podman:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_qemu: true
      run: test-multiplatform-podman

  multi-platform-buildah:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_qemu: true
      run: test-multiplatform-buildah

  multi-platform-chunkah:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_qemu: true
      run: test-multiplatform-chunkah

  multi-platform-build-chunked-oci:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_qemu: true
      run: test-multiplatform-build-chunked-oci

  multi-platform-rechunk:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_qemu: true
      run: test-multiplatform-rechunk

  iso-from-image:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-generate-iso-image

  iso-from-image-web-ui:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-generate-iso-web-ui

  iso-from-recipe:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      run: test-generate-iso-image

  container-podman-build:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_earthbuild: true
      run: test-container-podman-build

  container-podman-chunkah:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_earthbuild: true
      run: test-container-podman-chunkah

  container-podman-build-chunked-oci:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_earthbuild: true
      run: test-container-podman-build-chunked-oci

  container-podman-rechunk:
    uses: ./.github/workflows/run-test.yml
    secrets:
      TEST_SIGNING_SECRET: ${{ secrets.TEST_SIGNING_SECRET }}
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      fork_pr: ${{ inputs.fork_pr }}
      pr_event_number: ${{ inputs.pr_event_number }}
      install_earthbuild: true
      run: test-container-podman-rechunk
